image: node:6.5.0
cache:
  paths:
  - node_modules/
production:
  type: deploy
  script:
  - apt-get update -qy
  - echo "Y" |apt-get install libssl-dev
  - apt-get install -y rubygems
  - gem install dpl
  - dpl --provider=heroku --app=api-ohmybox-production --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - master
test:
  type: deploy
  script:
  - apt-get update -qy
  - echo "Y" |apt-get install libssl-dev
  - apt-get install -y rubygems
  - gem install dpl
  - dpl --provider=heroku --app=api-ohmybox-test --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - test
dev:
  type: deploy
  script:
  - apt-get update -qy
  - echo "Y" |apt-get install libssl-dev
  - apt-get install -y rubygems
  - gem install dpl
  - dpl --provider=heroku --app=api-ohmybox-dev --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - dev